name: Audit

on:
  push:
  schedule:
    - cron: 0 23 * * *
  workflow_dispatch:

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: StyraInc/setup-regal@main
        with:
          version: latest

      - id: app-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.REPOSAUR_APP_ID }}
          private_key: ${{ secrets.REPOSAUR_APP_PRIVATE_KEY }}

      - name: Audit
        uses: reposaur/repo-audit-action@main
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Lint
        run: regal lint --format=github ./github
